language: go

script:
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o docker-deploy docker-deploy.go

after_success:
  - ls -lh
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh docker-deploy
